"""create_imoveis_table

Revision ID: 01a98f049eef
Revises: 
Create Date: 2026-05-30 22:07:47.588630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a98f049eef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.String(length=120), nullable=False),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('tipo_anuncio', sa.String(length=20), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('quartos', sa.Integer(), nullable=True),
    sa.Column('banheiros', sa.Integer(), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('descricao', sa.String(length=2000), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imovel_cidade_tipo', 'imoveis', ['cidade', 'tipo'], unique=False)
    op.create_index('ix_imovel_preco', 'imoveis', ['preco'], unique=False)
    op.create_index('uq_imovel_fonte_externo', 'imoveis', ['fonte', 'id_externo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_imovel_fonte_externo', table_name='imoveis')
    op.drop_index('ix_imovel_preco', table_name='imoveis')
    op.drop_index('ix_imovel_cidade_tipo', table_name='imoveis')
    op.drop_table('imoveis')
    # ### end Alembic commands ###
